### PR TITLE
Before review

### PR DESCRIPTION
**Pull request by anenadic**
A quick initial review of the Before section to get some comments in.

### CODE REVIEW

**Comment by anenadic** [comment]
What Steve and I were not sure is what was meant by the "organising committee", so we assumed "steering committee" for the curriculum development separate from the actual development team. But we could have been wrong, so feel free to disregard those changes @tobyhodges.

**Comment by tobyhodges** [comment]
By "organising committee" I meant a group of people responsible for making the sprint happen. This was based on discussion with Library Carpentry sprint organisers who agreed that, especially for a multi-day event, it was crucial to have more than one person responsible for pulling the whole thing together.

However, I do think we should maybe say something like "Organising and running the sprint will be much easier if you have some help. If possible, create an organising committee of 2+ people responsible for making the sprint happen."

**Review by tobyhodges — APPROVED** [review]
Thanks @anenadic & @steve-crouch

**Comment by tobyhodges** [comment]
@all-contributors please add @anenadic for code

**Comment by tobyhodges** [comment]
@all-contributors please add @steve-crouch for code

**Pull request merged**
